#baseurl: /seek

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@4.1.0

current_seek_version: "1.16.0"
current_docker_tag: "1.16"

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

title: "FAIRDOM-SEEK Documentation"

exclude:
 - Gemfile*
 - .gitignore

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "help"
    values:
      permalink: /help/:basename
      sidebar: userguide
  -
    scope:
      path: "help/user-guide"
    values:
      permalink: /help/user-guide/:basename
      sidebar: userguide
  -
    scope:
      path: "tech"
    values:
      permalink: /tech/:basename
      sidebar: tech
  -
    scope:
      path: "tech/docker"
    values:
      permalink: /tech/docker/:basename
      sidebar: tech

  - scope:
      path: "tech/extended-metadata"
    values:
      permalink: /tech/extended-metadata/:basename
      sidebar: tech
  -
    scope:
      path: "tech/releases"
    values:
      permalink: /tech/releases/:basename
      sidebar: tech
  -
    scope:
      path: "tech/scripts"
    values:
      permalink: /tech/scripts/:basename
      sidebar: tech
  -
    scope:
      path: "tech/api"
    values:
      permalink: /tech/api/:basename
  -
    scope:
      path: "tech/api/definitions"
    values:
      permalink: /tech/api/definitions/:basename
  -
    scope:
      path: "tech/api/descriptions"
    values:
      permalink: /tech/api/descriptions/:basename
  -
    scope:
      path: "tech/api/examples"
    values:
      permalink: /tech/api/examples/:basename
  -
    scope:
      path: "tech/api/scripts"
    values:
      permalink: /tech/api/scripts/:basename
# adding type and layout to this scope is not working

theme_variables: 
  #git_host: GitHub
  #back_to_top: true
  #github_buttons: 
  #  position: top
  #  edit_me: true
  #  open_issue: true
  #  history: true
  # toc:
  #   min_headings: 2
  #   headings: 'h2'
  topnav:
    theme: light
    brand_logo: images/fairdom-seek-logo-header.png
    #github: true
    #twitter: false
  theme_color: 8cddf6
# theme color is not working! Trying c23669 from RDMkit doesn't help
